[package]
name = "impact-repo-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4.5.38", features = ["derive"] }
env_logger = "0.11.8"
git2 = "0.20.2"
itertools = "0.14.0"
log = "0.4.27"
rand = "0.9.1"
rand_distr = "0.5.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
statrs = "0.18.0"
